services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pgTestAuth@123
      POSTGRES_USER: admin
      POSTGRES_DB: postgresAuth
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/postgresAuth/data

volumes:
  db_data: